### PR TITLE
match Twig include tags with extra parameters

### PR DESCRIPTION
**Pull request by braver**
Ensures matches for just the file for tag style with extra parameters:

```
{% include 'template.html' with {'foo': 'bar'} %}
```

https://twig.symfony.com/doc/3.x/tags/include.html

Previously the regex would match from the first quote all the way to the last quote, but it shouldn't include the extra object with parameters. 

[Tested in regex101](https://regex101.com/r/U175RX/1)

### CODE REVIEW

**Comment by jfcherng** [comment]
This is what I use. There is no need to match the rest of the string after the filename actually.
https://github.com/jfcherng-sublime/ST-my-settings/blob/d81f8f60d107e4de43eae49cd71ca06ef656f75e/Packages/User/HyperClick.sublime-settings#L81-L87

**Comment by jfcherng** [comment]
This PR is fine for sure.

---

I am using https://github.com/jfcherng-sublime/ST-my-settings/blob/dc509e19387cfa9ad827e78ee3b4dbb7e2f83791/Packages/User/HyperClick.sublime-settings#L80-L86 (although `'` can be used in filename actually)

I think we don't have to match the rest of the string right after we have found the filename (the leading `{%` is quite a strong assertion). Anyway, merging them gives better performance and maintainability(?).

**Comment by braver** [comment]
Hm, yours has less repetition for sure, but for some of my test cases it doesn't work. You seem to have dropped the `{{ include('file', {params}) }}` form.


```html
<div id="regular-event">
    <section class="eticket">
        {{ include('Etickets/_eticket_header.html.twig', {
            event : event,
            production : production,
            type: 'regular'
        }) }}
        <div class="eticket-body">
            {% for ticket in tickets %}
                {{ include('Etickets/_eticket_body.html.twig', { ticket: ticket, type: 'regular'}) }}
            {% endfor %}
        </div>
    </section>
</div>

```

But yeah, you don't have to match all the way to the end of the statement. The opening of the statement and the initial include, etc., keyword are good indicators of the intent.

---

Edit: added example.

**Review by jfcherng — APPROVED** [review]

**Comment by braver** [comment]
@aziz are you still maintaining this package? I would like to help out.

**Comment by cristianl** [comment]
I cannot add collaborators but I'd vouch for @braver and @jfcherng

**Comment by braver** [comment]
@cristianl thanks for merging! Can you tag a release with the latest changes?

@aziz to consider: we could also move the repo to the [SublimeText](https://github.com/SublimeText) org where multiple experienced package developers maintain lots of packages.

**Comment by cristianl** [comment]
2.6.0 is now up. Sorry for the long delay.

**Pull request merged**
