### PR TITLE
Remove unnecessary disk IO (file existence checks) when resolving aliases

### PR DESCRIPTION
**Pull request by jfcherng**
- `alias_path = path.join(alias_source, self.str_path[len(alias) + 1:])` doen't looks robust enough.
- Calling `self.resolve_relative_to_dir()` will check a certain path is a file or not.

This PR remove unnecessary file existence checks.

### CODE REVIEW

**Comment by cristianl** [comment]
Great, thank you!

**Comment by jfcherng** [comment]
@cristianl 

 The webpack config does not mention alias name with a trailing slash https://webpack.js.org/configuration/resolve/#resolvealias but the example in this repo uses a trailing slash which my PR doesn't consider it as valid. Maybe webpack actually supports it or other bundlers 
do but I didn't try.

image

 If HyperClick is going to support trailing slash in the alias name, the trailing slash in `alias` should be trimmed before comparison in https://github.com/aziz/SublimeHyperClick/pull/55/files#diff-f63051dd6689d10256682a57e20532c2R88 and likewise in other places (or somewhere in its upstream). `path_parts[0]` is guaranteed to never has a slash.

**Comment by cristianl** [comment]
Thanks. I was going by the [vue-cli docs](https://github.com/vuejs/vue-cli/blame/357c99a3fb6be4a9e15bc9b4266533b1ae477642/docs/guide/css.md#L134) but it's implemented  as [`@` -> `src`](https://github.com/vuejs/vue-cli/blob/4de59d06acd2dce398b50f3e65e4979fc7f0e9f3/packages/%40vue/cli-service/lib/config/base.js#L49)

**Comment by cristianl** [comment]
By the way, Parcel uses a more declarative approach, [an `"alias"` field in package.json](https://parceljs.org/module_resolution.html) that HyperClick could load automatically.

I couldn't find a Webpack plugin or issue on the Webpack repo to add this functionality (I'm not sure it would fit Webpack's philosophy of high customizability and different rules for certain scenarios)

**Pull request merged**
