### PR TITLE
v2 scope based matching

### LINKED ISSUE #1: Enable by scope, not syntax file
Currently, your plugin depends on certain syntax files, otherwise it won't work. Personally, I'm using “JavaScript Next” to highlight JavaScript files. I understand I could easily add `JavaScript Next.sublime-syntax` to the settings, but wouldn't it be better to check the scope (e.g. `if scope.startswith('source.js')`) rather than for a syntax file?

### PR DESCRIPTION
**Pull request by braver**
The goal here is to fix #1, to base settings around scopes and selectors. This is cleaner because a language in Sublime is referred to by its scope name and plugins should not concern themselves with what a syntax filename on disk is. In a practical sense this eases support for alternative syntaxes, enables support for embedded syntax (e.g. JS inside an HTML file). And it's easier for users because a scope name is something they can find out and should know about, a syntax filename is more often than not hidden from them and undiscoverable.

I have some other goals here as well, in line with the above, mainly to reduce the code back down to one generic resolver. The JS resolver does a number of extra things that are useful for everyone. Finding project root directories is a generic concept and useful for many languages besides JS. The `valid_extensions` concept is similarly widely useful, and if not for a particular language there is no harm in leaving it out there. 

While I'm busy I may drop some constructs that were probably performance enhancements, we may have to bring those back. 

As it is, work in progress. It already seems to be working for my projects. Most visible change, and breaking to end users, is the settings. The new `selector` setting determines for which contexts we're active, `scopes` is a list of scopes where each scope has at least a regex and probably some other settings as well.

### CODE REVIEW

**Comment by braver** [comment]
So, I’ve been test driving this in my relatively simple setup and it seems pretty solid. What I’ve primarily got to do now is restore the special cases in the other revolvers, and then maybe double ceck for performance.

**Comment by cristianl** [comment]
Thanks for the PR! I've been using it for a few days and haven't noticed any perf degradation.

I ran into a small bug (aliases is a dict) but after fixing it I also added the missing parts from the JS (node modules) and the Sass resolver (underscore-prefixed filenames) to test them in my setup, and it's working well.

Should I add these changes as a commit to this PR?

**Comment by braver** [comment]
Oh that would be great! Make a PR against my branch and I’ll integrate it into this one.

**Comment by braver** [comment]
I have been using this for a while and it seems to be pretty solid. The big question then is how to make it available. Releasing this as a new version of the same package will break everyone's settings. There is no way for users to opt-in or pick their own moment for the upgrade: package control offers no such options. We could pre-announce via package update messages, but you still tend to miss a lot of users this way. It's not like there are millions of users out there, but it will be annoying to deal with.

The package could also use a "SEO" upgrade. HyperClick is a cool name, but it doesn't show up in package control if you look for "go to file" or and for "jump to file" it's low on the list among completely unrelated packages. It might not be an entirely bad idea to release this as a new package based on the fork, and redirect people to that. Maybe "HyperClick 2", or "Goto File" to make it easier to find. 

So, @cristianl ... 

- is there anything you think still needs to be done in this PR
- shall we 
  - A. release this as a new version of the package
      - update documentation
      - pre-announce to users
      - tell users how to upgrade 
      - add some keywords, rephrase repo description, etc. to make it easier to find
      - and do you want to do this yourself, or give me access to the repo to manage the transition?
  - or B. release as a new package based on the [fork](https://github.com/braver/SublimeHyperClick/tree/braver/v2-scope-based)

**Comment by cristianl** [comment]
@braver I've been using it and it's been solid here too!

The only unexpected behavior so far is that the `"annotations_enabled"` pref is ignored (as `sublime_plugin.EventListener` doesn't have the `is_applicable` class method).

This isn't much of a problem now that there's pretty much no delay before annotations appear, so maybe we could just remove this setting from the default settings file.

---

I lean towards just going ahead and releasing it as a regular update.

There's no data to back up this hunch, but I guess most users with overridden defaults were trying to work around issues/missing functionality with earlier releases.

The change that affects me the most is project settings. I could just write a script to fix my *sublime-project* files, but this seems easy enough to detect in the generic resolver (`project_settings` has a `"aliases"` or `"lookup_paths"` key) so we can at least prompt users to run a command via palette. 

As for SEO, I'd rather keep the current name but emphasize *jump to file* and *goto file* in the README title/first line.

**Comment by braver** [comment]
> The only unexpected behavior so far is that the "annotations_enabled" pref is ignored 

Well it's easy enough to support, we can bail out before any serious work is done. Maybe not 100% as efficient as the `is_applicable` method, but not in a way that anyone will notice.

> The change that affects me the most is project settings. I could just write a script to fix my sublime-project files, but this seems easy enough to detect in the generic resolver (project_settings has a "aliases" or "lookup_paths" key) so we can at least prompt users to run a command via palette.

Yes, that will be the most breaking thing probably. I can look into adding a validation that will alert users about what happened to their old settings.

> but emphasize jump to file and goto file in the README title/first line.

👌

**Comment by braver** [comment]
Alright, I added a little thing that checks for old settings on startup. If you switch projects after SublimeText was loaded you won't get warned again... maybe that's a good thing (less annoying, and you are probably already notified that you need to check your HyperClick settings) or maybe not (you forget about some project).

I also renamed the settings file because as far as users are concerned the package is never called "hyper_click", but always "HyperClick". If we're going to break, 2.0 is a good time to do so.

I updated the README and it should have enough information for users to upgrade if they were savvy enough to customize the settings in the first place. 

So, let me know if you want to see anything changed, but as far as I can tell it's ready to go and all in your hands now.

**Comment by niksy** [comment]
What is the status of this PR? What can we help with to get this merged?

**Comment by braver** [comment]
It's done in a technical sense, what needs to be done is tagging a release and communicating to users about it.

**Comment by cristianl** [comment]
@niksy Done.

@braver Sorry for delaying this PR for so long and thank you for your work!

I'm unable to properly communicate to users and help support v2 at the moment, but this PR is too stable and useful not to ship.

**Pull request merged**
