### PR TITLE
Add support for aliases

### PR DESCRIPTION
**Pull request by RichAyotte**
Add support for aliases.

This is almost a copy of https://github.com/aziz/SublimeHyperClick/pull/43 with comments addressed.

### CODE REVIEW

**Comment by xeontem** [comment]
As I understand this is support for webpack aliases. Can we merge it? Since this feature will be helpful for me.

**Comment by jfcherng** [comment]
@xeontem You can use your own implementation to overwrite *any* plugin's if the plugin author seems to be not responding. In case you don't know how to do it, just place your modified file with the same structure of this plugin like this https://github.com/jfcherng/my-Sublime-Text-settings/tree/master/Packages/HyperClick/hyper_click.

**Comment by cristianl** [comment]
Merged https://github.com/aziz/SublimeHyperClick/pull/43.

I didn't modify the logic in https://github.com/aziz/SublimeHyperClick/pull/43/files#r281014247 as it seems to work. I'll review and merge the differences in this PR later

**Comment by cristianl** [comment]
Merged this (https://github.com/aziz/SublimeHyperClick/pull/52) with the simpler logic on `resolve_from_alias()`

**Pull request merged**
