### PR TITLE
add jstl language support + mini refactoring to resolver

### PR DESCRIPTION
**Pull request by eparisio**
Hi i have made some change, i left the multi group logic to the jstlResolver, using a nested group logic.

i passed the entire view to the resolver, if needed for other infos in the future.

### CODE REVIEW

**Comment by cristianl** [comment]
Hi @eparisio! Could you provide me with an example project with jstl files?

I'm about to open a PR that makes some changes to the command and the annotator, and after amending my edits to include the jstl resolver, I'd like to check if jstl support is working in my branch.

**Comment by eparisio** [comment]
Hi @cristianl ,

i have no online project but a semple i find with a standard jsp/tag structure is there:
https://github.com/algaworks/ebook-mvc-servlets-jsp-jstl
the tag reference is inside consulta-produtos.jsp file (aw)

but you can create any folder with a similar structure:
root-
        ......
        |-->WEB-INF-
                              ......
                              |-->tags (tags)
                              |-->view (jsp)
if you need a different base folder override "vendor_dirs" "WEB-INF" in the configuration with a folder that will wrap all the files project. generally i think that all project will have a common folder (vendor_dirs) where start to search files. (https://stackoverflow.com/questions/5878774/standard-project-package-structure-of-a-j2ee-web-application)

**Comment by cristianl** [comment]
Thanks for pointing me to the example project! I was unfamiliar with JSP/JSTL, so I took a quick look. Please correct me if I’m wrong.

I believe this PR can be merged as the main feature (navigating to another project template) works and other languages are not affected. 

There are two apparent improvements that could be made to the jstl resolver, if you're interested in working on them for a future PR.

- When a tag is from a module from jstl’s standard lib (for instance, `c` and `fmt` in *consulta-produtos.jsp*) HyperClick should not annotate it unless it can provide a link to the lib’s docs (https://tomcat.apache.org/taglibs/standard/apidocs/ ?) or the source for that stdlib module.
- Imports made with `<c:import` should work, but right now they fail because they’re relative to some specific directory (*Estoque/WebContent* in the example). Where is this directory set? Is this based on some class name in the Java code?
  - Do all projects follow the same directory standard? A simple solution is to parse the current template filename to get whatever comes before the string `"/WebContent/WEB-INF/"`

**Review by anru — APPROVED** [review]
LGTM

**Comment by anru** [comment]
@aziz could you update package as well ?

**Comment by eparisio** [comment]
Hi @cristianl.

- generally all the external resource that reference to java class, are not real tag/jsp, but operation that are build in java and [.tld](https://docs.oracle.com/javaee/5/tutorial/doc/bnamu.html) files.
- yes i miss it, i will develop and check the import tag that will have a different behavior, it's a standard functional tag (it's a java reference to do some standard operation, in this case inject a file)
    - yes generally a standard project with spring-MVC will have the files inside the WEB-INF folder, at the moment it will cover the standard structure, but i think that changing the _vendor_dirs_ with an upper folder or a folder that will wrap all the jsp/tags of the project will works fine too

one think that can be done better i think is the lookup for vendor_dirs and file search.
actually i take the path of the current file, split the url to the vendor dir and than build the tag path from there, appending the regex results.
i don't know if there is a way to go up in folder with py/sublime.

**Pull request merged**
